# Generated by Django 5.1.6 on 2025-03-04 14:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camerashop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbmwgavqz/image/upload/v1741097511/default-avatar-icon-of-social-media-user-vector_ptam3f.jpg', max_length=255),
        ),
    ]
